### ISSUE TITLE
Move `sqlalchemy` to `snowflake` optional dep

### ISSUE THREAD

**Issue by korikuzma** [biocommons/anyvar#102]
> I'm not sure if we needed to add `sqlalchemy` to required dependencies (since not everyone will be using sqlalchemy). I think the optional `snowflake` dep handles this?

_Originally posted by @korikuzma in https://github.com/biocommons/anyvar/pull/101#discussion_r1809494436_
            

Will need to update docs to show optional deps and how to install

**Comment by jsstevenson** [comment]
(It would also need to be in the Postgres group)

**Comment by korikuzma** [comment]
@jsstevenson Oh that's my bad for not being familiar with the source code. I didn't realize we were using sqlalchemy with the postgres backend. I just assumed we were only using psycopg2. I'll close
