### ISSUE TITLE
Parameterize creating different translator

### ISSUE THREAD

**Issue by korikuzma** [biocommons/anyvar#56]
In #54 , we automatically choose the VrsPythonTranslator but should allow for different translators to be chosen. Example of what we could do:

```python
from os import environ
from enum import Enum

class TranslatorType(str, Enum):

  VRS_PYTHON = "vrs_python"
  VARIATION_NORM = "variation_normalizer"
  ...


TRANSLATOR_TYPE = environ.get("TRANSLATOR_TYPE", TranslatorType.VRS_PYTHON.value)

def create_translator(translator_type: TranslatorType = TRANSLATOR_TYPE) -> _Translator:
```

**Comment by theferrit32** [comment]
It might be controversial to say this but I think we should have anyvar implement some sort of policy to decide between the translators it can use to service a request based on both the data in the request and maybe some configuration on the server side. (e.g. `indel_auto_cnv_threshold=50`)

**Comment by ehclark** [comment]
I would vote for server configuration as a default overridable by request parameters.  For our labs, I think we will want VRS computation to reflect the variant caller output.  So we will want to force the use of the translator that matches the call type in the input VCF.

**Comment by korikuzma** [comment]
I think we can close this. We removed the variation normalizer in #63
