### ISSUE TITLE
Support Snowflake database as a storage backend

### ISSUE THREAD

**Issue by ehclark** [biocommons/anyvar#64]
Add an implementation of `anyvar.storage._Storage` that stores/queries a Snowflake database for VRS objects.

Snowflake storage implementation would be selected at runtime by specifying a `snowflake://...` storage URI in the `ANYVAR_STORAGE_URI` environment variable.  Format of the Snowflake storage URI is `snowflake://[account_identifier].snowflakecomputing.com/?[param=value]&[param=value]...` with the `account_identifier` and parameters as defined by the Snowflake Python connector: https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api

The Snowflake storage implementation should write VRS object batches asynchronously to avoid network waits before responding (since the Snowflake database will not be local).  Query operations operate solely on the stored VRS objects which means a query immediately after a batch-based VRS generation operation may not reflect the batch completely.

**Comment by mihaitodor** [comment]
Hey @ehclark, I have some experience with loading data into Snowflake. I built the integration in [Benthos](https://benthos.dev) using [Snowpipe](https://www.benthos.dev/docs/components/outputs/snowflake_put) as well as [direct inserts](https://www.benthos.dev/docs/components/outputs/sql_insert#drivers), in this case using their [Golang client library](https://github.com/snowflakedb/gosnowflake), but I assume the Python one is similar. If you need any help with adding this integration, happy to talk about it. I'm on the `biocommons` Slack if you use that one.
