### ISSUE TITLE
Add parameter to /vcf REST endpoint to control whether or not VRS IDs are computed for reference alleles

### ISSUE THREAD

**Issue by ehclark** [biocommons/anyvar#72]
https://github.com/ga4gh/vrs-python/issues/295 added a `compute_for_ref` parameter for VCF annotation.  This parameter should be available as an option in the /vcf REST endpoint.

Computes VRS IDs for all REF and ALT alleles:
```
PUT /vcf
```
Computes VRS IDs for all REF and ALT alleles:
```
PUT /vcf?for_ref=True
```
Computes VRS IDs for all ALT alleles:
```
PUT /vcf?for_ref=False
```

**Comment by ehclark** [comment]
@korikuzma @jsstevenson @larrybabb 
The changes for this and #71 require changes in vrs-python that have not been released.  Is the correct thing to do here create a 2.0.0a2 version of vrs-python?  And if so, how does that happen?

**Comment by korikuzma** [comment]
@ehclark To do this, we make a release on GitHub and that will trigger a GitHub action to make a pypi release. @larrybabb Is it okay if I go ahead and do this for @ehclark ?

**Comment by larrybabb** [comment]
Absolutely
