### ISSUE TITLE
postgres setup command typo

### ISSUE THREAD

**Issue by larrybabb** [biocommons/anyvar#78]
**Describe the bug**
The README-pg.md file (for postgres setup commands) has the following command for the 3rd step 
`cat src/anyvar/storage/postres_init.sql | psql -h localhost -U postgres -p 5432`
the `postres_init.sql` filename is mispelled, it should be `postgres_init.sql`

**To Reproduce**
1. Go to [src/anyvar/storage/README-pg.md](https://github.com/biocommons/anyvar/blob/main/src/anyvar/storage/README-pg.md)
2. See error

**Expected behavior**
The actual command should be edit to show the correct filename: 
`cat src/anyvar/storage/postgres_init.sql | psql -h localhost -U postgres -p 5432`

**Additional context**

**Comment by theferrit32** [comment]
Closed in #79
