### ISSUE TITLE
Add back missing response models to openapi.json

### ISSUE THREAD

**Issue by ehclark** [biocommons/anyvar#91]
Split off from https://github.com/biocommons/anyvar/issues/85

Same underlying problem as https://github.com/cancervariants/variation-normalization/issues/543

Changed the response models to return `Dict` instead of the types from `ga4gh.vrs.models`.  This allows the full, dereferenced VRS object to be returned from the API endpoints instead of the version produced by the serialization logic embedded in the model hierarchy.

**Comment by jsstevenson** [comment]
Closing in on a resolution in https://github.com/ga4gh/vrs-python/pull/435
